### ISSUE TITLE
Why are row groups useless?

### ISSUE THREAD

**Issue by ozgrakkurt** [sundy-li/pa#32]
Hey!

Why are row groups useless? You can skip over sections of files using statistics and bloom filters

**Comment by sundy-li** [comment]
`row groups` could be instead by multi files. We don't need to keep a large file that contains multiple row groups.

**Comment by sundy-li** [comment]
A single row group per file from https://docs.dremio.com/software/data-formats/parquet-files/

**Comment by ozgrakkurt** [comment]
> `row groups` could be instead by multi files. We don't need to keep a large file that contains multiple row groups.

But you might require finer granularity for skipping data. So you might need to make files too small as far as I can understand?

**Comment by ozgrakkurt** [comment]
> A single row group per file from https://docs.dremio.com/software/data-formats/parquet-files/

for example I index ethereum data and I query it by address of contracts. Which performs best if I have about 10MB files with 8 to 16 row groups and I skip the row groups based on statistics. How would it work with one file per row group?

**Comment by sundy-li** [comment]
> But you might require finer granularity for skipping data

Yes, we need page indexes to skip the data by pages, this is done inside [`databend`](https://github.com/datafuselabs/databend/blob/main/src/query/storages/common/index/src/page_index.rs#L89) but not in strawboat.

**Comment by ozgrakkurt** [comment]
But that only enables skipping parts of individual columns, it is not possible to skip all columns based on one column with that approach afaik

**Comment by sundy-li** [comment]
In databend, we will generate min/max/bloom filter index for all columns, it's in another meta file.

**Comment by ozgrakkurt** [comment]
thanks a lot for the info!
